[package]
name = "photoslibrary"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Interact with Apple Photos.app library"

[dependencies]
anyhow = "1"
futures = "0.3"
libsql = "0.6"
tokio = { version = "1.43", features = ["full"] }
chrono = "0.4"
